name: CI

on:
  push:
  schedule:
    - cron: "0 */8 * * *"

  workflow_dispatch:

env:
  super_secret: ${{ secrets.token }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Execute script
        run: |
           chmod +x ./fork_all.sh
           ./fork_all.sh
        shell: bash
